# https://prettier.io/docs/en/options.html

# Specify Correct Parser
parser: babel
filepath: ''

# Main Settings
printWidth: 120
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: as-needed
trailingComma: all
bracketSpacing: true
jsxBracketSameLint: false
jsxSingleQuote: false
arrowParens: avoid
endOfLine: lf

# process always
requirePragma: false
insertPragma: false

# for Markdown
# proseWrap: preserve
# for HTML
# htmlWhitespaceSensitivity: css

overrides:
  - files: "*.json"
    options:
      parser: json
  - files:
      - "*.md"
      - "*.markdown"
    options:
      parser: markdown
  - files:
      - "*.ts"
      - "*.tsx"
    options:
      parser: typescript
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      parser: yaml

